#!/bin/bash
#
# Copyright (C) 2025, Advanced Micro Devices, Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# This file is automatically generated using the do script
set -o pipefail
ABS_PATH=$(pwd)
export PROJECT_NAME=example_design

#Production Board
export BOARD=XIL_VEK385
export CHIP_PART=xc2ve3858-ssva2112-2MP-e-S

echo -e "\n # Hardware platform generation has started at: $(date '+%Y-%m-%d %H:%M:%S')"
echo -e " Detailed Vivado logs are available at: ${ABS_PATH}/vivado.log"
echo -e " Expected to take approximately 40 minutes to complete...\n"

vivado -mode tcl -source create_platform.tcl >> $ABS_PATH/cmd.log
if [ $? != 0 ]; then tail $ABS_PATH/cmd.log && exit 1; fi

echo " # Hardware platform generation completed at: $(date '+%Y-%m-%d %H:%M:%S')"
